vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       avatar:
           uri_prefix: /upload/images/avatar
           upload_destination: '%kernel.project_dir%/public/upload/images/avatar'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
       galaxy:
           uri_prefix: /upload/images/galaxy
           upload_destination: '%kernel.project_dir%/public/upload/images/galaxy'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
       planets:
           uri_prefix: /upload/images/planets
           upload_destination: '%kernel.project_dir%/public/upload/images/planets'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
       lifeform:
           uri_prefix: /upload/images/lifeform
           upload_destination: '%kernel.project_dir%/public/upload/images/lifeform'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
